<a href="https://colab.research.google.com/github/benarjii/miniproject_sem6/blob/main/Evaluating_RAG_Pipelines_o3_mini.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install haystack-ai
!pip install "datasets>=2.6.1"
!pip install "sentence-transformers>=3.0.0"

Collecting haystack-ai
  Downloading haystack_ai-2.11.2-py3-none-any.whl.metadata (14 kB)
Collecting haystack-experimental (from haystack-ai)
  Downloading haystack_experimental-0.8.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (3.1.6)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (4.23.0)
Collecting lazy-imports (from haystack-ai)
  Downloading lazy_imports-0.4.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (10.6.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (3.4.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (2.0.2)
Requirement already satisfied: openai>=1.56.1 in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (1.69.0)
Collecting posthog!=3.12.0 (from haystack-ai)
  Downloading posthog-3.23.0-py2.py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: pydantic in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (2.11.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (2.8.2)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0 in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (9.0.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (4.67.1)
Requirement already satisfied: typing-extensions>=4.7 in /usr/local/lib/python3.11/dist-packages (from haystack-ai) (4.13.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.56.1->haystack-ai) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.56.1->haystack-ai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.56.1->haystack-ai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai>=1.56.1->haystack-ai) (0.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from openai>=1.56.1->haystack-ai) (1.3.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from posthog!=3.12.0->haystack-ai) (1.17.0)
Collecting monotonic>=1.5 (from posthog!=3.12.0->haystack-ai)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog!=3.12.0->haystack-ai)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->haystack-ai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->haystack-ai) (2.33.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic->haystack-ai) (0.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->haystack-ai) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->haystack-ai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->haystack-ai) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->haystack-ai) (2025.1.31)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->haystack-ai) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema->haystack-ai) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema->haystack-ai) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema->haystack-ai) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema->haystack-ai) (0.24.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->openai>=1.56.1->haystack-ai) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.56.1->haystack-ai) (0.14.0)
Downloading haystack_ai-2.11.2-py3-none-any.whl (451 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 451.6/451.6 kB 14.5 MB/s eta 0:00:00
Downloading posthog-3.23.0-py2.py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.0/85.0 kB 5.3 MB/s eta 0:00:00
Downloading haystack_experimental-0.8.0-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 4.4 MB/s eta 0:00:00
Downloading lazy_imports-0.4.0-py3-none-any.whl (12 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Installing collected packages: monotonic, lazy-imports, backoff, posthog, haystack-experimental, haystack-ai
Successfully installed backoff-2.2.1 haystack-ai-2.11.2 haystack-experimental-0.8.0 lazy-imports-0.4.0 monotonic-1.6 posthog-3.23.0
Collecting datasets>=2.6.1
  Downloading datasets-3.5.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (3.18.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets>=2.6.1)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (4.67.1)
Collecting xxhash (from datasets>=2.6.1)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets>=2.6.1)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.12.0,>=2023.1.0 (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets>=2.6.1)
  Downloading fsspec-2024.12.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (3.11.14)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (0.29.3)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.6.1) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (6.2.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.6.1) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets>=2.6.1) (4.13.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.6.1) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.6.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.6.1) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets>=2.6.1) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=2.6.1) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=2.6.1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets>=2.6.1) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.6.1) (1.17.0)
Downloading datasets-3.5.0-py3-none-any.whl (491 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.2/491.2 kB 25.8 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.7 MB/s eta 0:00:00
Downloading fsspec-2024.12.0-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.9/183.9 kB 15.9 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 11.1 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 16.4 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.0
    Uninstalling fsspec-2025.3.0:
      Successfully uninstalled fsspec-2025.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.12.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-cupti-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-nvrtc-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-nvrtc-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-runtime-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cuda-runtime-cu12 12.5.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cudnn-cu12 9.3.0.75 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cufft-cu12==11.2.1.3; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cufft-cu12 11.2.3.61 which is incompatible.
torch 2.6.0+cu124 requires nvidia-curand-cu12==10.3.5.147; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-curand-cu12 10.3.6.82 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusolver-cu12==11.6.1.9; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusolver-cu12 11.6.3.83 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cusparse-cu12==12.3.1.170; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cusparse-cu12 12.5.1.3 which is incompatible.
torch 2.6.0+cu124 requires nvidia-nvjitlink-cu12==12.4.127; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-nvjitlink-cu12 12.5.82 which is incompatible.
Successfully installed datasets-3.5.0 dill-0.3.8 fsspec-2024.12.0 multiprocess-0.70.16 xxhash-3.5.0
Requirement already satisfied: sentence-transformers>=3.0.0 in /usr/local/lib/python3.11/dist-packages (3.4.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (4.50.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (1.14.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (0.29.3)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers>=3.0.0) (11.1.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (2024.12.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (4.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers>=3.0.0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers>=3.0.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers>=3.0.0) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.0.0) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.0.0) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.0.0) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=3.0.0) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=3.0.0) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers>=3.0.0) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=3.0.0) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=3.0.0) (2025.1.31)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00

In [ ]:
from haystack.telemetry import tutorial_running

tutorial_running(35)

In [ ]:
from datasets import load_dataset
from haystack import Document

dataset = load_dataset("vblagoje/PubMedQA_instruction", split="train")
dataset = dataset.select(range(1000))
all_documents = [Document(content=doc["context"]) for doc in dataset]
all_questions = [doc["instruction"] for doc in dataset]
all_ground_truth_answers = [doc["response"] for doc in dataset]

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/498 [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/274M [00:00<?, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/986k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/272458 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [ ]:
from typing import List
from haystack import Pipeline
from haystack.components.embedders import SentenceTransformersDocumentEmbedder
from haystack.components.writers import DocumentWriter
from haystack.document_stores.in_memory import InMemoryDocumentStore
from haystack.document_stores.types import DuplicatePolicy

document_store = InMemoryDocumentStore()

document_embedder = SentenceTransformersDocumentEmbedder(model="sentence-transformers/all-MiniLM-L6-v2")
document_writer = DocumentWriter(document_store=document_store, policy=DuplicatePolicy.SKIP)

indexing = Pipeline()
indexing.add_component(instance=document_embedder, name="document_embedder")
indexing.add_component(instance=document_writer, name="document_writer")

indexing.connect("document_embedder.documents", "document_writer.documents")

indexing.run({"document_embedder": {"documents": all_documents}})

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/32 [00:00<?, ?it/s]

{'document_writer': {'documents_written': 1000}}

In [ ]:
import os
from getpass import getpass
from haystack.components.builders import AnswerBuilder, ChatPromptBuilder
from haystack.dataclasses import ChatMessage
from haystack.components.embedders import SentenceTransformersTextEmbedder
from haystack.components.generators.chat import OpenAIChatGenerator
from haystack.components.retrievers.in_memory import InMemoryEmbeddingRetriever

if "OPENAI_API_KEY" not in os.environ:
    os.environ["OPENAI_API_KEY"] = getpass("Enter OpenAI API key:")

template = [
    ChatMessage.from_user(
        """
        You have to answer the following question based on the given context information only.

        Context:
        {% for document in documents %}
            {{ document.content }}
        {% endfor %}

        Question: {{question}}
        Answer:
        """
    )
]

rag_pipeline = Pipeline()
rag_pipeline.add_component(
    "query_embedder", SentenceTransformersTextEmbedder(model="sentence-transformers/all-MiniLM-L6-v2")
)
rag_pipeline.add_component("retriever", InMemoryEmbeddingRetriever(document_store, top_k=3))
rag_pipeline.add_component("prompt_builder", ChatPromptBuilder(template=template))
rag_pipeline.add_component("generator", OpenAIChatGenerator(model="o3-mini-2025-01-31"))
rag_pipeline.add_component("answer_builder", AnswerBuilder())

rag_pipeline.connect("query_embedder", "retriever.query_embedding")
rag_pipeline.connect("retriever", "prompt_builder.documents")
rag_pipeline.connect("prompt_builder.prompt", "generator.messages")
rag_pipeline.connect("generator.replies", "answer_builder.replies")
rag_pipeline.connect("retriever", "answer_builder.documents")

Enter OpenAI API key:··········

<haystack.core.pipeline.pipeline.Pipeline object at 0x7a86c5cfc910>
🚅 Components
  - query_embedder: SentenceTransformersTextEmbedder
  - retriever: InMemoryEmbeddingRetriever
  - prompt_builder: ChatPromptBuilder
  - generator: OpenAIChatGenerator
  - answer_builder: AnswerBuilder
🛤️ Connections
  - query_embedder.embedding -> retriever.query_embedding (List[float])
  - retriever.documents -> prompt_builder.documents (List[Document])
  - retriever.documents -> answer_builder.documents (List[Document])
  - prompt_builder.prompt -> generator.messages (List[ChatMessage])
  - generator.replies -> answer_builder.replies (List[ChatMessage])

In [ ]:
question = "Do high levels of procalcitonin in the early phase after pediatric liver transplantation indicate poor postoperative outcome?"

response = rag_pipeline.run(
    {
        "query_embedder": {"text": question},
        "prompt_builder": {"question": question},
        "answer_builder": {"query": question},
    }
)
print(response["answer_builder"]["answers"][0].data)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Yes, high early postoperative procalcitonin levels are associated with poor outcomes after pediatric liver transplantation. According to the study, patients with elevated procalcitonin on postoperative day 2 experienced higher International Normalized Ratio values on day 5, an increased incidence of primary graft non-function, and longer stays in the pediatric intensive care unit and on mechanical ventilation. These findings indicate that high procalcitonin levels signal a worse postoperative prognosis.

In [ ]:
import random

questions, ground_truth_answers, ground_truth_docs = zip(
    *random.sample(list(zip(all_questions, all_ground_truth_answers, all_documents)), 25)
)

In [ ]:
rag_answers = []
retrieved_docs = []

for question in list(questions):
    response = rag_pipeline.run(
        {
            "query_embedder": {"text": question},
            "prompt_builder": {"question": question},
            "answer_builder": {"query": question},
        }
    )
    print(f"Question: {question}")
    print("Answer from pipeline:")
    print(response["answer_builder"]["answers"][0].data)
    print("\n-----------------------------------\n")

    rag_answers.append(response["answer_builder"]["answers"][0].data)
    retrieved_docs.append(response["answer_builder"]["answers"][0].documents)

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is ulcerative proctitis a frequent location of paediatric-onset UC and not a minor disease : a population-based study?
Answer from pipeline:
Based on the study, while ulcerative proctitis (UP) represented 25% of paediatric‐onset UC cases at diagnosis, it was not a benign or minor form of the disease. Nearly half of these patients experienced colonic extension over time—with cumulative risks reaching 45% at 5 years and 52% at 10 years—and their outcomes (including risks for needing anti-TNF‐α therapy and colectomy) were similar to those with more extensive disease. Thus, even though UP may seem limited at onset, its progression and therapeutic requirements indicate that it is far from being a minor disease.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does hypercholesterolemia increase the production of leukotriene B4 in neutrophils by enhancing the nuclear localization of 5-lipoxygenase?
Answer from pipeline:
Yes, the data indicate that hypercholesterolemia increases leukotriene B4 production in neutrophils through mechanisms that include enhanced nuclear localization of 5-lipoxygenase. Although the total levels of 5-LO remain similar, hypercholesterolemia is associated with increased nuclear localization and phosphorylation of 5-LO (as well as ERK1/2), which promotes LTB4 synthesis.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does ultrasound elastography correlate treatment response by antiviral therapy in patients with chronic hepatitis C?
Answer from pipeline:
Yes, ultrasound elastography does correlate with treatment response in patients with chronic hepatitis C. The context shows that liver stiffness (LS) measured by FibroScan and the liver fibrosis index (LFI) assessed by real-time tissue elastography both decreased in patients who achieved a sustained virological response (SVR) and increased in most patients who did not, indicating that changes in tissue elasticity are reflective of antiviral treatment efficacy.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is pseudomonas aeruginosa in CF and non-CF homes found predominantly in drains?
Answer from pipeline:
Yes, according to the context, Pseudomonas aeruginosa is predominantly found in drains. The study noted that 28% of sampled drains yielded the organism at least once, and a mixed linear model estimated that 6.3% of drain samples contained P. aeruginosa, which is more than eight times the recovery rate from any other household environment.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does preoperative anemia increase postoperative morbidity in elective cranial neurosurgery?
Answer from pipeline:
Yes, preoperative anemia does increase postoperative morbidity in elective cranial neurosurgery. The study shows that anemic patients had significantly higher 30-day morbidity (25.9% vs 14.14% in non-anemic patients) and that the odds for postoperative morbidity were elevated (OR = 1.29; 95% CI: 1.03–1.61) in the anemic group.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does loss of Frzb and Sfrp1 differentially affect joint homeostasis in instability-induced osteoarthritis?
Answer from pipeline:
Yes. The study found that deleting Frzb and Sfrp1 has different effects on joint homeostasis in the DMM model of osteoarthritis. Frzb deletion led to significantly increased cartilage damage in the tibia compared to wild-type mice, although subchondral bone thickness was similar between Frzb(-/-) and control mice. In contrast, Sfrp1 deletion did not markedly affect cartilage damage scores but resulted in significant differences in subchondral bone properties compared to littermates.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does extracellular vesicle-driven information mediate the long-term effects of particulate matter exposure on coagulation and inflammation pathways?
Answer from pipeline:
Based on the provided context, yes. The study showed that increased expression of 17 EV-encapsulated microRNAs (EVmiRNAs) is associated with particulate matter and metal exposure, and among these, three (miR-302b, miR-200c, and miR-30d) are linked to disruptions in inflammatory and coagulation markers. This evidence supports the hypothesis that extracellular vesicle-driven information, via their carried microRNAs, mediates some of the long-term effects of particulate matter exposure on coagulation and inflammation pathways.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is reduction of methicillin-resistant Staphylococcus aureus infection in long-term care possible while maintaining patient socialization : A prospective randomized clinical trial?
Answer from pipeline:
Answer: Yes. The study demonstrated that using a novel, minimally invasive decolonization program—which included universal decolonization with intranasal mupirocin, chlorhexidine baths, and on‐site screening without patient isolation—resulted in a 65% reduction in MRSA infections while maintaining patients’ activities of daily living and socialization.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does bile deficiency induce changes in intestinal glucose absorption in mice?
Answer from pipeline:
Yes, bile deficiency (as induced by biliary duct ligation or external biliary drainage) significantly increases intestinal (duodenal mucosal) glucose absorption in mice. This heightened absorption is accompanied by a marked rise in the protein expression of the sodium‐glucose cotransporter SGLT1, while the levels of GLUT2 remain largely unchanged. Additionally, administering bile acids can almost reverse this increased absorption, underscoring the role of bile in regulating intestinal glucose uptake.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does computer simulation of lumbar flexion show shear of the facet capsular ligament?
Answer from pipeline:
Yes, the simulation indicated that shear is indeed present. The finite element model of facet joint flexion demonstrated prominent inhomogeneous in-plane and through-plane shear deformations in the lumbar facet capsular ligament.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does cryptosporidium parvum rhomboid1 have an activity in microneme protein CpGP900 cleavage?
Answer from pipeline:
Yes, based on the provided context, Cryptosporidium parvum rhomboid 1 (CpROM1) does exhibit activity in cleaving the microneme protein CpGP900. The study showed that in co-transformed yeast and co-transfected mammalian cells, CpROM1 interacted with CpGP900, and the cleavage product of CpGP900 was detected only when CpROM1 was present. This indicates that CpGP900 is a substrate of CpROM1.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Do nomograms incorporating serum C-reactive protein effectively predict mortality before and after surgical treatment of renal cell carcinoma?
Answer from pipeline:
Yes, the nomograms that incorporate serum C-reactive protein effectively predict mortality both before and after surgery for renal cell carcinoma. In the study, CRP was the factor with the largest effect in all nomograms, and both the preoperative and postoperative models showed high concordance indices—0.889 and 0.893, respectively for renal cell carcinoma-specific mortality (and similarly high indices for overall mortality) that were significantly better than the Mayo Clinic stage, size, grade, and necrosis score. This suggests that including CRP in the nomograms improves their predictive accuracy for patient outcomes.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does targeting factor VIII expression to platelets for hemophilia A gene therapy induce an apparent thrombotic risk in mice?
Answer from pipeline:
Answer: No, targeting factor VIII expression to platelets for hemophilia A gene therapy does not induce an apparent thrombotic risk. The study found that platelets expressing FVIII were neither hyper‐activated nor hyper‐responsive, indicating that this gene therapy approach does not elevate the risk for thrombosis.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is tumor-related leukocytosis associated with poor radiation response and clinical outcome in uterine cervical cancer patients?
Answer from pipeline:
Yes. In the study, patients with tumor-related leukocytosis (TRL) had a significantly lower rate of complete remission after radiation, as well as reduced long-term outcomes. For instance, the 10-year locoregional failure-free survival (69% vs. 87%) and overall survival (63% vs. 81%) were markedly poorer in TRL-positive patients compared to those without TRL. These findings indicate that TRL is indeed associated with both poor radiation response and clinical outcome in uterine cervical cancer patients.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is sTin2 VNTR polymorphism associated with comorbid tobacco use and mood disorders?
Answer from pipeline:
Yes, the study found that the STin2 VNTR polymorphism is associated with comorbid tobacco use disorder and mood disorders. Specifically, carrying the STin2.12 allele is positively associated with having both disorders (Odds ratio = 3.07), while being homozygous for the STin2.10 allele (STin2.10/10 genotype) is negatively associated (Odds ratio = 0.34).

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Do sugar-Sweetened Beverages Are the Main Sources of Added Sugar Intake in the Mexican Population?
Answer from pipeline:
Yes, sugar-sweetened beverages are the main source of added sugar intake in the Mexican population, contributing 69% of the added sugars.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does mood influence the Concordance of Subjective and Objective Measures of Sleep Duration in Older Adults?
Answer from pipeline:
Yes, mood does influence the concordance between subjective and objective measures of sleep duration in older adults. In the pilot study described, a significant discrepancy was observed between self-reported sleep duration (assessed by ecological momentary assessment) and objective measurement using actigraphy. Importantly, the magnitude of this discrepancy was explained by the patient's mood status (p = 0.020), indicating that variations in mood can affect how older adults perceive their sleep duration relative to what is objectively recorded.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is actual lowering effect of metabolic syndrome on serum prostate-specific antigen levels partly concealed by enlarged prostate : results from a large-scale population-based study?
Answer from pipeline:
Answer: Yes, the study’s results indicate that the true lowering effect of metabolic syndrome on serum PSA levels is partly concealed by the presence of an enlarged prostate. When adjustments were made for the larger prostate volume in men with metabolic syndrome, both PSA density and PSA mass density were found to be significantly lower compared to men without MetS, and the estimated decline in mean serum PSA levels was more pronounced.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is the transposable element environment of human genes associated with histone and expression changes in cancer?
Answer from pipeline:
Yes, the transposable element environment is associated with histone modifications and with changes in gene expression in cancer. The context indicates that genes with nearby TEs display greater changes in histone enrichment between normal and cancer conditions, and that differentially expressed genes tend to have larger variations in histone modification linked to the presence of specific TEs.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Are low serum 25-hydroxyvitamin d concentrations associated with increased risk for melanoma and unfavourable prognosis?
Answer from pipeline:
Yes, according to the study's findings, low serum 25-hydroxyvitamin D concentrations are associated with an increased risk for melanoma as well as a poorer prognosis. Melanoma patients had significantly lower vitamin D levels compared to controls. Additionally, patients with the lowest vitamin D levels (<10 ng/ml) exhibited greater tumor thickness and significantly inferior overall survival compared to those with higher levels (>20 ng/ml).

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does ataxia Severity correlate with White Matter Degeneration in Spinocerebellar Ataxia Type 7?
Answer from pipeline:
Based solely on the provided context, the study found that ataxia severity (measured by the Scale for the Assessment and Rating of Ataxia) significantly correlates with white matter degeneration—but only when evaluated using mean diffusivity. Specifically, significant associations were observed in regions critical for motor control and visuospatial processing, such as the cerebellar white matter, middle occipital white matter, superior cerebellar peduncle, and bilateral anterior thalamic radiation. However, no significant correlations were noted when using fractional anisotropy as the measure.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Do a new model for the standardization of experimental burn wounds?
Answer from pipeline:
The model combines a unique burn apparatus with an innovative animal fixation method to generate reproducible burn injuries of varying sizes and depths. In this approach, rats are exposed to a metal device heated to a precise temperature (either 60 °C, 70 °C, or 80 °C) for a fixed duration (10 seconds). This produces clearly defined burn patterns: a superficial second‐degree burn (involving 28% of the dermis) at 60 °C; a deep second‐degree burn (72% of the dermis) at 70 °C; and a full‐thickness, third‐degree burn (affecting 100% of the dermis) at 80 °C. The method provides a standardized means to create well-characterized injuries for experimental studies, thereby enhancing the reproducibility and comparability of burn research outcomes.

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Does cardiac-specific ablation of synapse-associated protein SAP97 in mice decrease potassium currents but not sodium current?
Answer from pipeline:
Yes, cardiac-specific ablation of SAP97 in mice led to a decrease in potassium currents (specifically IK1, Ito, and IKur) without affecting the sodium current (INa).

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is pattern of first recurrent lesions in pancreatic cancer : hepatic relapse associated with dismal prognosis and portal vein invasion?
Answer from pipeline:
Yes, based on the context hepatic relapse is linked to a dismal prognosis—it showed significantly shorter overall survival and was an independent prognostic factor (p<0.001). Moreover, pathological portal vein invasion was identified as the only independent risk factor for hepatic relapse (p=0.045).

-----------------------------------

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Question: Is eGFR expression associated with poor outcome in cutaneous squamous cell carcinoma?
Answer from pipeline:
Based on the provided context about cutaneous squamous cell carcinoma (CSCC), EGFR overexpression in the primary tumors was found to be associated with lymph node progression, TNM stage progression, and increased proliferation (as indicated by Ki-67 staining). Furthermore, EGFR overexpression along with a poor grade of differentiation were identified as the strongest independent variables defining lymph node metastasis and clinical progression in CSCC.

Thus, yes, overexpression of EGFR is associated with a poor outcome in CSCC.

-----------------------------------

While each evaluator is a component that can be run individually in Haystack, they can also be added into a pipeline. This way, we can construct an `eval_pipeline` that includes all evaluators for the metrics we want to evaluate our pipeline on.

In [ ]:
from haystack.components.evaluators.document_mrr import DocumentMRREvaluator
from haystack.components.evaluators.faithfulness import FaithfulnessEvaluator
from haystack.components.evaluators.sas_evaluator import SASEvaluator

eval_pipeline = Pipeline()
eval_pipeline.add_component("doc_mrr_evaluator", DocumentMRREvaluator())
eval_pipeline.add_component("faithfulness", FaithfulnessEvaluator())
eval_pipeline.add_component("sas_evaluator", SASEvaluator(model="sentence-transformers/all-MiniLM-L6-v2"))

results = eval_pipeline.run(
    {
        "doc_mrr_evaluator": {
            "ground_truth_documents": list([d] for d in ground_truth_docs),
            "retrieved_documents": retrieved_docs,
        },
        "faithfulness": {
            "questions": list(questions),
            "contexts": list([d.content] for d in ground_truth_docs),
            "predicted_answers": rag_answers,
        },
        "sas_evaluator": {"predicted_answers": rag_answers, "ground_truth_answers": list(ground_truth_answers)},
    }
)

100%|██████████| 25/25 [01:08<00:00,  2.76s/it]

### Constructing an Evaluation Report

Once we've run our evaluation pipeline, we can also create a full evaluation report. Haystack provides an `EvaluationRunResult` which we can use to display an `aggregated_report` 👇

In [ ]:
from haystack.evaluation.eval_run_result import EvaluationRunResult

inputs = {
    "question": list(questions),
    "contexts": list([d.content] for d in ground_truth_docs),
    "answer": list(ground_truth_answers),
    "predicted_answer": rag_answers,
}

evaluation_result = EvaluationRunResult(run_name="pubmed_rag_pipeline", inputs=inputs, results=results)
evaluation_result.aggregated_report()

{'metrics': ['doc_mrr_evaluator', 'faithfulness', 'sas_evaluator'],
 'score': [1.0, np.float64(1.0), np.float64(0.7191868603229523)]}

#### Extra: You can also see a detailed report with the scores for each sample in your dataset, and we will choose the output format as DataFrame

In [ ]:
results_df = evaluation_result.detailed_report(output_format='df')
results_df

,question,contexts,answer,predicted_answer,doc_mrr_evaluator,faithfulness,sas_evaluator
0,Is ulcerative proctitis a frequent location of...,[Natural history of paediatric-onset ulcerativ...,UP is frequent in paediatric-onset UC and shou...,"Based on the study, while ulcerative proctitis...",1.0,1.0,0.754055
1,Does hypercholesterolemia increase the product...,[Neutrophils can synthesize leukotriene B4 (LT...,Hypercholesterolemia increases LTB4 production...,"Yes, the data indicate that hypercholesterolem...",1.0,1.0,0.880061
2,Does ultrasound elastography correlate treatme...,[To investigate the relationship between tissu...,"With a few exceptions, SVR improved LS. All pa...","Yes, ultrasound elastography does correlate wi...",1.0,1.0,0.454401
3,Is pseudomonas aeruginosa in CF and non-CF hom...,[For patients with cystic fibrosis (CF) Pseudo...,These findings implicate drains as important p...,"Yes, according to the context, Pseudomonas aer...",1.0,1.0,0.687885
4,Does preoperative anemia increase postoperativ...,[Preoperative anemia may affect postoperative ...,Preoperative anemia in elective cranial neuros...,"Yes, preoperative anemia does increase postope...",1.0,1.0,0.895171
5,Does loss of Frzb and Sfrp1 differentially aff...,[To investigate the specific role of Frizzled-...,"Using the DMM model, we demonstrated that FRZB...",Yes. The study found that deleting Frzb and Sf...,1.0,1.0,0.693589
6,Does extracellular vesicle-driven information ...,[Continuous exposure to particulate air pollut...,The study's findings support the hypothesis th...,"Based on the provided context, yes. The study ...",1.0,1.0,0.610129
7,Is reduction of methicillin-resistant Staphylo...,[Antibiotic resistance is a challenge in long-...,On-site MRSA surveillance with targeted decolo...,Answer: Yes. The study demonstrated that using...,1.0,1.0,0.739027
8,Does bile deficiency induce changes in intesti...,[Biliary tract obstruction is a common clinica...,Bile deficiency in the intestine upregulates t...,"Yes, bile deficiency (as induced by biliary du...",1.0,1.0,0.851983
9,Does computer simulation of lumbar flexion sho...,[The lumbar facet capsular ligament (FCL) is a...,We found that in-plane and through-plane shear...,"Yes, the simulation indicated that shear is in...",1.0,1.0,0.664086
10,Does cryptosporidium parvum rhomboid1 have an ...,[Apicomplexan parasites actively release trans...,Our results showed that CpROM1 is an active pr...,"Yes, based on the provided context, Cryptospor...",1.0,1.0,0.670142
11,Do nomograms incorporating serum C-reactive pr...,[To incorporate C-reactive protein into nomogr...,We have generated nomograms incorporating seru...,"Yes, the nomograms that incorporate serum C-re...",1.0,1.0,0.852763
12,Does targeting factor VIII expression to plate...,[Essentials Platelet-Factor (F) VIII gene ther...,Background Targeting factor (F) VIII expressio...,"Answer: No, targeting factor VIII expression t...",1.0,1.0,0.791194
13,Is tumor-related leukocytosis associated with ...,[To evaluate response to radiation and clinica...,This study reveals the aggressive nature of ce...,"Yes. In the study, patients with tumor-related...",1.0,1.0,0.565599
14,Is sTin2 VNTR polymorphism associated with com...,[There is a significant comorbidity between mo...,The STin2.12 allele is positively and the STin...,"Yes, the study found that the STin2 VNTR polym...",1.0,1.0,0.753602
15,Do sugar-Sweetened Beverages Are the Main Sour...,[Sugar intake has been associated with an incr...,The average intake of added sugars in the Mexi...,"Yes, sugar-sweetened beverages are the main so...",1.0,1.0,0.709053
16,Does mood influence the Concordance of Subject...,[Sleep plays a central role in maintaining hea...,The discrepancy classically observed between o...,"Yes, mood does influence the concordance betwe...",1.0,1.0,0.780488
17,Is actual lowering effect of metabolic syndrom...,[To clarify the lowering effect of metabolic s...,The actual lowering effect of MetS on serum PS...,"Answer: Yes, the study’s results indicate that...",1.0,1.0,0.769994
18,Is the transposable element environment of hum...,[Only 2 % of the human genome code for protein...,"Taken together, these results suggest that the...","Yes, the transposable element environment is a...",1.0,1.0,0.540590
19,Are low serum 25-hydroxyvitamin d concentratio...,[Low vitamin D status (serum 25(OH)D concentra...,Our data support the concept that serum 25(OH)...,"Yes, according to the study's findings, low se...",1.0,1.0,0.698746
20,Does ataxia Severity correlate with White Matt...,[There is a scarcity of information on the eff...,These results suggest a significant contributi...,"Based solely on the provided context, the stud...",1.0,1.0,0.748383
21,Do a new model for the standardization of expe...,[Burns are common and recurrent events treated...,"This is a safe, reliable, easy to construct an...",The model combines a unique burn apparatus wit...,1.0,1.0,0.638115
22,Does cardiac-specific ablation of synapse-asso...,[Membrane-associated guanylate kinase (MAGUK) ...,These data suggest that ablation of SAP97 in t...,"Yes, cardiac-specific ablation of SAP97 in mic...",1.0,1.0,0.597989
23,Is pattern of first recurrent lesions in pancr...,[The aim of this study was to evaluate pattern...,Hepatic relapse was associated with a dismal p...,"Yes, based on the context hepatic relapse is l...",1.0,1.0,0.850275
24,Is eGFR expression associated with poor outcom...,[Cutaneous squamous cell carcinoma (CSCC) is t...,We demonstrate that EGFR overexpression has pr...,Based on the provided context about cutaneous ...,1.0,1.0,0.782353

Having our evaluation results as a dataframe can be quite useful. For example, below we can use the pandas dataframe to filter the results to the top 3 best scores for semantic answer similarity (`sas_evaluator`) as well as the bottom 3 👇

In [ ]:
# o3-mini
import pandas as pd

top_3 = results_df.nlargest(3, "sas_evaluator")
bottom_3 = results_df.nsmallest(3, "sas_evaluator")
pd.concat([top_3, bottom_3])

,question,contexts,answer,predicted_answer,doc_mrr_evaluator,faithfulness,sas_evaluator
4,Does preoperative anemia increase postoperativ...,[Preoperative anemia may affect postoperative ...,Preoperative anemia in elective cranial neuros...,"Yes, preoperative anemia does increase postope...",1.0,1.0,0.895171
1,Does hypercholesterolemia increase the product...,[Neutrophils can synthesize leukotriene B4 (LT...,Hypercholesterolemia increases LTB4 production...,"Yes, the data indicate that hypercholesterolem...",1.0,1.0,0.880061
11,Do nomograms incorporating serum C-reactive pr...,[To incorporate C-reactive protein into nomogr...,We have generated nomograms incorporating seru...,"Yes, the nomograms that incorporate serum C-re...",1.0,1.0,0.852763
2,Does ultrasound elastography correlate treatme...,[To investigate the relationship between tissu...,"With a few exceptions, SVR improved LS. All pa...","Yes, ultrasound elastography does correlate wi...",1.0,1.0,0.454401
18,Is the transposable element environment of hum...,[Only 2 % of the human genome code for protein...,"Taken together, these results suggest that the...","Yes, the transposable element environment is a...",1.0,1.0,0.540590
13,Is tumor-related leukocytosis associated with ...,[To evaluate response to radiation and clinica...,This study reveals the aggressive nature of ce...,"Yes. In the study, patients with tumor-related...",1.0,1.0,0.565599